---
sudo: enabled
dist: trusty

language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=full

script:
  - cargo build --verbose
  - cargo test --verbose

after_failure:
  - cat Cargo.lock
